[package]
name = "ics_timesheet_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ical]
version = "0.7.*"
default-features = false
features = ["ical", "vcard"]
